#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Lei Zhou, Linaro
#
# The command line.
#
# `check` is the most valuable command here and the one a new user runs
# first: it answers "would a measurement taken here be valid?" without
# measuring, and it changes nothing. `explain` is the second: it says what a
# config will do and how long it will take, which is how someone catches a
# mistake before spending forty minutes measuring the wrong thing.
#
# WHAT THIS BUILD DOES NOT DO. The pipeline is collect, derive, attribute,
# report. This is the collecting half. Derivation and attribution exist as
# their own tools and are not driven from here yet — the component that joins
# the two halves is deliberately built last, on both sides, so that neither
# half is shaped around a guess about the other. `run` therefore stops after
# records and says so rather than implying a verdict is coming.
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import config as config_mod                             # noqa: E402
import preconditions                                    # noqa: E402
import session as session_mod                           # noqa: E402
import victims                                          # noqa: E402
from adapters import LocalAdapter                       # noqa: E402


def _load(path):
    try:
        return config_mod.load(path)
    except config_mod.ConfigError as e:
        e.render(sys.stderr)
        raise SystemExit(2)
    except IOError as e:
        print("cannot read %s: %s" % (path, e), file=sys.stderr)
        raise SystemExit(2)


def _capabilities(describe):
    lines = []
    t = describe["tracing"]
    if t["available"]:
        lines.append("kernel-event collection: available (%s, per-CPU ring "
                     "buffers; no global tracing state is taken)"
                     % t["source"])
    else:
        lines.append("kernel-event collection: UNAVAILABLE — %s" % t["note"])
    lines.append("privilege: %s"
                 % ("root" if describe["privileged"]
                    else "unprivileged; most preconditions cannot be fixed "
                         "from here"))
    lines.append("kernel: %s, %s"
                 % (describe["kernel_release"],
                    "PREEMPT_RT" if "PREEMPT_RT" in describe["kernel_version"]
                    else "no PREEMPT_RT"))
    return lines


def cmd_check(args):
    cfg = _load(args.config)
    ad = LocalAdapter()
    plan = session_mod.build_plan(cfg, ad)
    results = preconditions.check_all(ad, plan)
    print("mcib check — %s" % cfg["_source"])
    print("session `%s`: %s on cpu%d, %d run%s"
          % (cfg["session"], ", ".join(cfg["victim"]["metrics"]),
             cfg["victim"]["cpu"], config_mod.estimate(cfg)["runs"],
             "" if config_mod.estimate(cfg)["runs"] == 1 else "s"))
    print("")
    ok = preconditions.render(results, _capabilities(ad.describe()),
                              verbose=args.verbose)
    if args.json:
        print(json.dumps([r.as_dict() for r in results], indent=2,
                         sort_keys=True))
    return 0 if ok else 1


def cmd_explain(args):
    cfg = _load(args.config)
    est = config_mod.estimate(cfg)
    v, a = cfg["victim"], cfg["aggressors"]
    blocks = session_mod.run_order(cfg)

    print("%s will:" % cfg["_source"])
    print("")
    print("  measure   %s" % ", ".join(
        "%s (%s)" % (m, victims.get(m).description.split(" — ")[0])
        for m in v["metrics"] if m in victims.MANIFEST))
    print("  on        cpu%d, SCHED_FIFO priority %d, in domain `%s`"
          % (v["cpu"], v["priority"], v["domain"]))
    print("  under     %s" % ", ".join(a["conditions"]))
    print("            generated by %s on cpu%s, intensity %d"
          % (a["tool"], ",".join(str(c) for c in a["cpus"]), a["intensity"]))
    if "io" in a["conditions"]:
        fs = session_mod._filesystem_of(a["io_path"])
        if fs and fs.get("ram_backed"):
            print("  NOTE      the io aggressor writes to %s, which is %s — "
                  "a RAM" % (a["io_path"], fs["type"]))
            print("            filesystem. It will contend for memory, not "
                  "for a storage device.")
        elif fs:
            print("  io writes %s on %s (%s)"
                  % (a["io_path"], fs["mount_point"], fs["type"]))
    print("  counters  %s, set `%s`"
          % (" and ".join(cfg["counters"]["state"]), cfg["counters"]["set"]))
    print("  repeats   %d" % cfg["repeats"])
    print("")
    print("  That is %d runs of %d iterations, in %d blocks. Each block warms "
          "the board" % (est["runs"], v["iterations"], len(blocks)))
    print("  for %ds and then runs its conditions in rotation, so that drift "
          "over the" % session_mod.WARMUP_SECONDS)
    print("  session falls across the conditions rather than into one of "
          "them.")
    print("")
    for m, n in sorted(est["intervals_per_run"].items()):
        note = ""
        if victims.get(m).intervals_per_iteration != 1:
            note = ("  (%d per iteration — this metric is measured in both "
                    "directions)" % victims.get(m).intervals_per_iteration)
        print("  %-8s %d intervals per run%s" % (m, n, note))
    print("")
    print("  Expected duration   %s" % config_mod.human_duration(
        est["seconds"]))
    print("  Expected disk       %d MB of records" % est["megabytes"])
    print("  Output              %s" % cfg["output"])
    print("")
    if args.runs:
        print("  Run order:")
        for b in blocks:
            print("    warm-up, then: %s"
                  % ", ".join(r["tag"] for r in b["runs"]))
        print("")
    print("  Nothing has been measured. Run `mcib check %s` to find out "
          "whether" % cfg["_source"])
    print("  a measurement here would be valid.")
    return 0


def cmd_init(args):
    text = config_mod.init_text(args.journey)
    if args.output and args.output != "-":
        if os.path.exists(args.output) and not args.force:
            print("%s already exists; pass --force to overwrite"
                  % args.output, file=sys.stderr)
            return 2
        with open(args.output, "w") as f:
            f.write(text)
        print("wrote %s" % args.output)
        print("Next: mcib explain %s" % args.output)
    else:
        sys.stdout.write(text)
    return 0


def cmd_collect(args, announce_stage=True):
    cfg = _load(args.config)
    ad = LocalAdapter()
    plan = session_mod.build_plan(cfg, ad)

    results = preconditions.check_all(ad, plan)
    failures = [r for r in results if r.state == preconditions.FAIL]
    if failures and not args.force:
        print("mcib: preconditions are not met; nothing has been measured.")
        print("")
        preconditions.render(results, _capabilities(ad.describe()))
        print("")
        print("Re-run `mcib check %s` after fixing these, or pass --force to "
              "measure anyway" % cfg["_source"])
        print("(a forced run records the failures in its conditions and is "
              "not a valid result).")
        return 1
    if failures and args.force:
        print("mcib: FORCED — %d precondition%s not met. This session's "
              "conditions will record that." % (len(failures),
                                                "" if len(failures) == 1
                                                else "s"))

    os.makedirs(cfg["output"], exist_ok=True)
    with open(os.path.join(cfg["output"], "resolved-config.yaml"), "w") as f:
        f.write(config_mod.resolved_yaml(cfg))
    with open(os.path.join(cfg["output"], "preconditions.json"), "w") as f:
        json.dump([r.as_dict() for r in results], f, indent=2, sort_keys=True)
        f.write("\n")

    s = session_mod.Session(cfg, ad)
    outcomes = s.run()

    manifest = {
        "kind": "mcib.session",
        "version": 1,
        "session": cfg["session"],
        "config": config_mod.resolved_yaml(cfg),
        "runs": outcomes,
        "domain": ad.describe(),
    }
    with open(os.path.join(cfg["output"], "session.json"), "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True, default=str)
        f.write("\n")

    failed = [o for o in outcomes if o.get("failed")]
    drifted = [o for o in outcomes if o.get("drifted")]
    print("")
    print("%d runs, %d failed, %d with drifted conditions"
          % (len(outcomes), len(failed), len(drifted)))
    for o in failed:
        print("  FAILED %s: %s" % (o["tag"], o.get("error", "see .out")))
    for o in drifted:
        print("  DRIFT  %s: %s" % (o["tag"], ", ".join(
            "%s %s->%s" % (d["field"], d["before"], d["after"])
            for d in o["drift"])))
    print("")
    print("Records and conditions: %s" % cfg["output"])
    print("Resolved configuration: %s"
          % os.path.join(cfg["output"], "resolved-config.yaml"))
    if announce_stage:
        print("")
        print("This build stops after records. Deriving intervals and "
              "attributing them")
        print("are separate tools; the component that drives the whole "
              "pipeline from this")
        print("config is not in this build.")
    return 1 if failed else 0


def cmd_run(args):
    return cmd_collect(args, announce_stage=True)


def cmd_victims(args):
    for m in victims.metrics():
        victims.describe(m)
        print("")
    return 0


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    ap = argparse.ArgumentParser(
        prog="mcib",
        description="sequence and collect mixed-criticality interference "
                    "measurements")
    sub = ap.add_subparsers(dest="command")

    p = sub.add_parser("check", help="preconditions only; changes nothing")
    p.add_argument("config")
    p.add_argument("--json", action="store_true")
    p.add_argument("--verbose", action="store_true")
    p.set_defaults(fn=cmd_check)

    p = sub.add_parser("explain", help="what this config will do, and for "
                                       "how long")
    p.add_argument("config")
    p.add_argument("--runs", action="store_true",
                   help="also list every run in order")
    p.set_defaults(fn=cmd_explain)

    p = sub.add_parser("init", help="write a commented, working config")
    p.add_argument("journey", choices=sorted(config_mod.JOURNEYS))
    p.add_argument("-o", "--output", default="-")
    p.add_argument("--force", action="store_true")
    p.set_defaults(fn=cmd_init)

    p = sub.add_parser("collect", help="check, then measure; stop after "
                                       "records")
    p.add_argument("config")
    p.add_argument("--force", action="store_true",
                   help="measure even though preconditions failed; the "
                        "result is not valid and says so")
    p.set_defaults(fn=cmd_collect)

    p = sub.add_parser("run", help="the pipeline. In this build that is "
                                   "collection only")
    p.add_argument("config")
    p.add_argument("--force", action="store_true")
    p.set_defaults(fn=cmd_run)

    p = sub.add_parser("victims", help="the victim manifest")
    p.set_defaults(fn=cmd_victims)

    args = ap.parse_args(argv)
    if not getattr(args, "fn", None):
        ap.print_help()
        return 2
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
